### No.-1

In [1]:
import numpy as np

In [2]:
def vander_matrix(lis, N, increasing=False):
    
    if not increasing:
        matrix = np.array([x**(N-1-i) for x in lis for i in range(N)]).reshape(lis.size,N)
    elif increasing:
        matrix = np.array([x**i for x in lis for i in range(N)]).reshape(lis.size,N)
    
    return matrix

In [3]:
lis = np.array([1,2,3,4,5])
N = 3
ven_matrix = vander_matrix(lis,5,True)

In [4]:
print(ven_matrix)

[[  1   1   1   1   1]
 [  1   2   4   8  16]
 [  1   3   9  27  81]
 [  1   4  16  64 256]
 [  1   5  25 125 625]]


### No.-2

In [11]:
def moving_average(array, k) :
    array_shape = array.shape[0]    
    moving_avg = np.zeros(array_shape - k + 1)
    
    for i in range(k, array_shape + 1):
        moving_avg[i-k] = array[i-k:i].mean()
    return moving_avg

In [12]:
a = np.array([3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3
mov_arr=moving_average(a,k)
print(mov_arr)

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
